name: i_baza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  hive: ^2.2.3
  shared_preferences: ^2.2.2
  hive_flutter: any
  path_provider: ^2.1.2
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  gap: ^3.0.1
  pinput: ^3.0.1
  image_picker: ^1.0.7
  open_file: ^3.3.2
  share_plus: ^7.2.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  objectbox_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/authentication/
    - assets/profile/